language: csharp
solution: "./Facebook.ApiClient.Entities.sln"
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0 
script:
- dotnet restore ./Facebook.ApiClient.Entities/Facebook.ApiClient.Entities.csproj
- dotnet build ./Facebook.ApiClient.Entities/Facebook.ApiClient.Entities.csproj /t:Rebuild /p:Configuration=Release /detailedsummary /v:n
