language: csharp
solution: "./Facebook.ApiClient.Entities.sln"
script:
- dotnet restore ./Facebook.ApiClient.Entities/Facebook.ApiClient.Entities.csproj
- dotnet build ./Facebook.ApiClient.Entities/Facebook.ApiClient.Entities.csproj /t:Rebuild /p:Configuration=Release /detailedsummary /v:n
